#!/usr/bin/env python3
"""Generate Paper 1 physics-gate ablation evidence and LaTeX inputs."""
from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path

from pcfmcw_isac.paper1_physics_gate_ablation import run_paper1_physics_gate_ablation


def _pct(x: float) -> str:
    return f"{100.0 * x:.2f}\\%"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output-dir", default="artifacts/paper1/physics_gate_ablation")
    parser.add_argument("--paper-dir", default="paper")
    args = parser.parse_args()
    out = Path(args.output_dir)
    paper = Path(args.paper_dir)
    out.mkdir(parents=True, exist_ok=True)
    result = run_paper1_physics_gate_ablation()

    (out / "results.json").write_text(json.dumps(result, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    with (out / "records.csv").open("w", newline="", encoding="utf-8") as f:
        fields = ["range_m", "radial_velocity_mps", "any_profile_feasible", "gated_class", "ungated_class", "gated_physics_valid", "ungated_physics_valid", "selection_changed"]
        w = csv.DictWriter(f, fieldnames=fields)
        w.writeheader()
        for row in result["records"]:
            w.writerow({k: row[k] for k in fields})

    s = result["summary"]
    table = f"""% AUTO-GENERATED by scripts/run_paper1_physics_gate_ablation.py; do not hand-edit.
\\begin{{table}}[t]
\\centering
\\caption{{Paper-1 deterministic physics-gate ablation on the boundary-aware range--velocity grid.}}
\\label{{tab:p1gateablation}}
\\begin{{tabular}}{{lrrrr}}
\\toprule
Selector & Selected & Selection rate & Invalid & Invalid/selected\\\\
\\midrule
Gated & {s['gated_selected']} & {_pct(s['gated_selection_rate'])} & {s['gated_invalid_selections']} & 0.00\\%\\\\
Ungated & {s['ungated_selected']} & {_pct(s['ungated_selection_rate'])} & {s['ungated_invalid_selections']} & {_pct(s['ungated_invalid_selection_rate_conditional'])}\\\\
\\bottomrule
\\end{{tabular}}
\\end{{table}}
"""
    (paper / "paper1_physics_gate_ablation_table.tex").write_text(table, encoding="utf-8")

    invalid_coords = " ".join(f"({r['range_m']},{r['radial_velocity_mps']})" for r in result["records"] if r["ungated_class"] == "INVALID_SELECTED_ACTION")
    alt_coords = " ".join(f"({r['range_m']},{r['radial_velocity_mps']})" for r in result["records"] if r["ungated_class"] == "INVALID_SELECTED_ACTION" and r["gated_class"] == "VALID_SELECTED_ACTION")
    figure = f"""% AUTO-GENERATED by scripts/run_paper1_physics_gate_ablation.py; do not hand-edit.
\\newcommand{{\\figPaperOneGateAblation}}{{%
\\begin{{figure*}}[t]
\\centering
\\begin{{tikzpicture}}
\\begin{{axis}}[width=0.94\\textwidth,height=6.2cm,xlabel={{Range (m)}},ylabel={{Radial velocity (m/s)}},xmin=-1,xmax=61,ymin=-62,ymax=62,grid=major,legend style={{font=\\footnotesize,at={{(0.5,-0.20)}},anchor=north,legend columns=2}}]
\\addplot+[only marks,mark=x] coordinates {{{invalid_coords}}};
\\addplot+[only marks,mark=o] coordinates {{{alt_coords}}};
\\addplot+[domain=0:22.36,samples=2] {{8.4055}};
\\addplot+[domain=0:22.36,samples=2] {{-8.4055}};
\\addplot+[domain=0:56.21,samples=2,dashed] {{48.6676}};
\\addplot+[domain=0:56.21,samples=2,dashed] {{-48.6676}};
\\legend{{Ungated invalid selection,Gate recovers valid alternative,Parking $|v|$ boundary,Parking $-|v|$ boundary,High-mobility $|v|$ boundary,High-mobility $-|v|$ boundary}}
\\end{{axis}}
\\end{{tikzpicture}}
\\caption{{Boundary-aware Paper-1 ablation. Crosses mark states where the nominal ungated selector chooses a configuration outside its deterministic FMCW support; circles identify the subset for which physics gating instead exposes a valid alternative. Lines show the two profiles' unambiguous-velocity boundaries; range support is additionally enforced in the machine-readable evidence. This is deterministic analytical/simulation-model evidence, not a hardware measurement.}}
\\label{{fig:p1gateablation}}
\\end{{figure*}}%
}}
"""
    (paper / "paper1_physics_gate_ablation_figure.tex").write_text(figure, encoding="utf-8")

    print(json.dumps(s, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
