#!/usr/bin/env python3
"""Generate Paper 1 physics-gate ablation evidence and LaTeX inputs."""
from __future__ import annotations
import argparse, csv, json
from pathlib import Path
from pcfmcw_isac.paper1_physics_gate_ablation import run_paper1_physics_gate_ablation

def _pct(x: float) -> str:
    return f"{100.0 * x:.2f}\\%"

def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output-dir", default="artifacts/paper1/physics_gate_ablation")
    parser.add_argument("--paper-dir", default="paper")
    args = parser.parse_args(); out=Path(args.output_dir); paper=Path(args.paper_dir); out.mkdir(parents=True,exist_ok=True)
    result=run_paper1_physics_gate_ablation()
    (out/"results.json").write_text(json.dumps(result,indent=2,sort_keys=True)+"\n",encoding="utf-8")
    fields=["range_m","radial_velocity_mps","any_profile_feasible","gated_class","ungated_class","gated_physics_valid","ungated_physics_valid","selection_changed"]
    with (out/"records.csv").open("w",newline="",encoding="utf-8") as f:
        w=csv.DictWriter(f,fieldnames=fields); w.writeheader()
        for row in result["records"]: w.writerow({k:row[k] for k in fields})
    s=result["summary"]
    supportable=s["physically_feasible_states"]
    recoverable=s["ungated_invalid_gated_valid_alternative_cases"]
    ungated_valid=supportable-recoverable
    table=f"""% AUTO-GENERATED by scripts/run_paper1_physics_gate_ablation.py; do not hand-edit.
\\begin{{table}}[t]
\\centering
\\caption{{Primary Paper-1 gate ablation conditioned on the {supportable} states for which at least one declared action is physically valid.}}
\\label{{tab:p1gateablation}}
\\begin{{tabular}}{{lrrr}}
\\toprule
Selector & Valid & Invalid despite alternative & Invalid fraction\\\\
\\midrule
Gated & {supportable} & 0 & 0.00\\%\\\\
Ungated & {ungated_valid} & {recoverable} & {_pct(recoverable/supportable)}\\\\
\\bottomrule
\\end{{tabular}}
\\vspace{{1mm}}
\\footnotesize Full stress grid: {s['total_states']} states; {s['physically_infeasible_states']} are outside the complete action-set support. The ungated full-grid invalid count is {s['ungated_invalid_selections']}/{s['ungated_selected']} ({_pct(s['ungated_invalid_selection_rate_all_states'])}), reported only as a boundary-stress diagnostic.
\\end{{table}}
"""
    (paper/"paper1_physics_gate_ablation_table.tex").write_text(table,encoding="utf-8")
    invalid=" ".join(f"({r['range_m']},{r['radial_velocity_mps']})" for r in result["records"] if r["ungated_class"]=="INVALID_SELECTED_ACTION")
    alt=" ".join(f"({r['range_m']},{r['radial_velocity_mps']})" for r in result["records"] if r["ungated_class"]=="INVALID_SELECTED_ACTION" and r["gated_class"]=="VALID_SELECTED_ACTION")
    figure=f"""% AUTO-GENERATED by scripts/run_paper1_physics_gate_ablation.py; do not hand-edit.
\\newcommand{{\\figPaperOneGateAblation}}{{%
\\begin{{figure*}}[t]
\\centering
\\begin{{tikzpicture}}
\\begin{{axis}}[width=0.94\\textwidth,height=6.2cm,xlabel={{Range (m)}},ylabel={{Radial velocity (m/s)}},xmin=-1,xmax=61,ymin=-62,ymax=62,grid=major,legend style={{font=\\footnotesize,at={{(0.5,-0.20)}},anchor=north,legend columns=2}}]
\\addplot+[only marks,mark=x] coordinates {{{invalid}}};
\\addplot+[only marks,mark=o] coordinates {{{alt}}};
\\addplot+[domain=0:22.36,samples=2] {{8.4055}}; \\addplot+[domain=0:22.36,samples=2] {{-8.4055}};
\\addplot+[domain=0:56.21,samples=2,dashed] {{48.6676}}; \\addplot+[domain=0:56.21,samples=2,dashed] {{-48.6676}};
\\legend{{Ungated invalid selection,Recoverable: valid alternative exists,Parking $|v|$ boundary,Parking $-|v|$ boundary,High-mobility $|v|$ boundary,High-mobility $-|v|$ boundary}}
\\end{{axis}}\\end{{tikzpicture}}
\\caption{{Boundary-aware deterministic stress grid. Crosses mark capability-blind selections outside the selected profile's support; circles identify the scientifically primary recoverable subset where another declared action is physically valid. The grid is designed around capability boundaries and is not a real-driving probability distribution.}}
\\label{{fig:p1gateablation}}
\\end{{figure*}}%}}
"""
    (paper/"paper1_physics_gate_ablation_figure.tex").write_text(figure,encoding="utf-8")
    print(json.dumps(s,indent=2,sort_keys=True))
if __name__=="__main__": main()
